import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';
import { useLanguage } from '../../context/LanguageContext';
import { votingService } from '../../services/votingService';
import jsPDF from 'jspdf';
import './VotingResults.css';

const VotingResults = () => {
  const { meetingId, votingId } = useParams();
  const navigate = useNavigate();
  const { user, client } = useAuth();
  const { t, language } = useLanguage();
  const [results, setResults] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadResults();
  }, [votingId]);

  const loadResults = async () => {
    try {
      const response = await votingService.getResults(votingId);
      setResults(response.data);
    } catch (error) {
      console.error('Error loading results:', error);
    } finally {
      setLoading(false);
    }
  };

  const addPdfBranding = (doc, voting) => {
    const pageCount = doc.getNumberOfPages();
    const clientName = (client?.name || 'ASOCOLCI').toUpperCase();
    const generatedAt = new Date().toLocaleString(language === 'es' ? 'es-ES' : 'en-US');

    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();

      // Header
      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.text(clientName, 12, 9);
      doc.setFont('helvetica', 'normal');
      doc.text(`${voting?.title || '-'} · ${language === 'es' ? 'Votación' : 'Voting'}`, 12, 14);
      doc.setLineWidth(0.2);
      doc.line(10, 20, pageWidth - 10, 20);

      // Footer
      doc.setLineWidth(0.2);
      doc.line(10, pageHeight - 14, pageWidth - 10, pageHeight - 14);
      doc.setFontSize(8);
      doc.setFont('helvetica', 'italic');
      doc.text(
        `${language === 'es' ? 'Generado por' : 'Generated by'} BOARD QUORUM · Plataforma de gobernanza · ${generatedAt}`,
        12,
        pageHeight - 8
      );
      doc.text(
        `${language === 'es' ? 'Pág' : 'Page'} ${i}/${pageCount}`,
        pageWidth - 30,
        pageHeight - 8
      );
    }
  };

  const generatePDF = () => {
    if (!results) return;

    const { voting, results: voteResults, votes, totalVotes, majority, majorityValidation } = results;
    if (!totalVotes || totalVotes === 0) {
      alert(language === 'es'
        ? 'No se puede generar el PDF porque no hay votos emitidos.'
        : 'Cannot generate PDF because there are no votes cast.');
      return;
    }
    const doc = new jsPDF();
    
    // Configuración
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 28;
    let yPos = margin;
    const lineHeight = 7;
    
    // Título
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text(language === 'es' ? 'Resultados de Votación' : 'Voting Results', margin, yPos);
    yPos += lineHeight * 2;
    
    // Título de la votación
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    const titleLines = doc.splitTextToSize(voting.title, pageWidth - 2 * margin);
    doc.text(titleLines, margin, yPos);
    yPos += lineHeight * (titleLines.length + 1);
    
    // Fecha
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    const date = new Date().toLocaleDateString(language === 'es' ? 'es-ES' : 'en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
    doc.text(`${language === 'es' ? 'Generado el' : 'Generated on'}: ${date}`, margin, yPos);
    yPos += lineHeight * 2;
    
    // Resumen
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text(language === 'es' ? 'Resumen' : 'Summary', margin, yPos);
    yPos += lineHeight;
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`${language === 'es' ? 'Total de Votos' : 'Total Votes'}: ${totalVotes}`, margin, yPos);
    yPos += lineHeight;
    
    if (majority !== undefined) {
      doc.text(`${language === 'es' ? 'Mayoría Requerida' : 'Required Majority'}: ${majority}`, margin, yPos);
      yPos += lineHeight;
    }
    
    if (majorityValidation) {
      doc.setFont('helvetica', 'bold');
      const status = majorityValidation.approved 
        ? (language === 'es' ? 'APROBADA' : 'APPROVED')
        : (language === 'es' ? 'RECHAZADA' : 'REJECTED');
      doc.text(`${language === 'es' ? 'Resultado' : 'Result'}: ${status}`, margin, yPos);
      yPos += lineHeight;
      doc.setFont('helvetica', 'normal');
      doc.text(majorityValidation.message, margin, yPos);
      yPos += lineHeight * 2;
    } else {
      yPos += lineHeight;
    }
    
    // Distribución de votos
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text(language === 'es' ? 'Distribución de Votos' : 'Vote Distribution', margin, yPos);
    yPos += lineHeight;
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    voteResults.forEach((result, index) => {
      const percentage = totalVotes > 0 ? (result.votes / totalVotes) * 100 : 0;
      const text = `${result.option}: ${result.votes} ${language === 'es' ? 'votos' : 'votes'} (${percentage.toFixed(1)}%)`;
      
      // Verificar si necesitamos una nueva página
      if (yPos > doc.internal.pageSize.getHeight() - 30) {
        doc.addPage();
        yPos = margin;
      }
      
      doc.text(text, margin, yPos);
      yPos += lineHeight;
    });
    
    yPos += lineHeight;
    
    // §9 JV — Voto institucional Junta de Vigilancia
    const jvVotePdf = votes.find(isJvVote);
    if (jvVotePdf) {
      if (yPos > doc.internal.pageSize.getHeight() - 30) { doc.addPage(); yPos = margin; }
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.text(language === 'es' ? 'Voto Institucional — Junta de Vigilancia' : 'Institutional Vote — Oversight Board', margin, yPos);
      yPos += lineHeight;
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text(
        language === 'es'
          ? `Representante JV (${clientName}): ${jvVotePdf.member_name}   |   Sentido del voto: ${jvVotePdf.option}`
          : `JV Representative (${clientName}): ${jvVotePdf.member_name}   |   Vote: ${jvVotePdf.option}`,
        margin, yPos
      );
      yPos += lineHeight * 1.5;
    }

    // Detalle de votos
    if (yPos > doc.internal.pageSize.getHeight() - 50) {
      doc.addPage();
      yPos = margin;
    }
    
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text(language === 'es' ? 'Detalle de Votos' : 'Vote Details', margin, yPos);
    yPos += lineHeight;
    
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    
    // Encabezados de tabla
    doc.setFont('helvetica', 'bold');
    doc.text(language === 'es' ? 'Miembro' : 'Member', margin, yPos);
    doc.text(language === 'es' ? 'Rol' : 'Role', margin + 80, yPos);
    doc.text(language === 'es' ? 'Voto' : 'Vote', margin + 130, yPos);
    yPos += lineHeight;
    
    // Línea separadora
    doc.setLineWidth(0.5);
    doc.line(margin, yPos, pageWidth - margin, yPos);
    yPos += lineHeight;
    
    // Votos individuales
    doc.setFont('helvetica', 'normal');
    votes.forEach((vote) => {
      // Verificar si necesitamos una nueva página
      if (yPos > doc.internal.pageSize.getHeight() - 20) {
        doc.addPage();
        yPos = margin;
      }
      
      const memberName = doc.splitTextToSize(vote.member_name, 70);
      const role = doc.splitTextToSize(vote.role || '-', 40);
      const option = vote.option;
      
      doc.text(memberName, margin, yPos);
      doc.text(role, margin + 80, yPos);
      doc.text(option, margin + 130, yPos);
      yPos += lineHeight * Math.max(memberName.length, role.length, 1);
    });
    
    addPdfBranding(doc, voting);
    // Guardar PDF
    const fileName = `Resultados_Votacion_${voting.title.replace(/[^a-z0-9]/gi, '_')}_${Date.now()}.pdf`;
    doc.save(fileName);
  };

  if (loading) return <div className="loading">{language === 'es' ? 'Cargando resultados...' : 'Loading results...'}</div>;
  if (!results) return <div className="error">{language === 'es' ? 'No se pudieron cargar los resultados' : 'Could not load results'}</div>;

  const { voting, results: voteResults, votes, totalVotes, majority, majorityValidation } = results;
  const maxVotes = Math.max(...voteResults.map(r => parseInt(r.votes) || 0), 0);

  // §9 JV: identificar el voto institucional (primer miembro JV que votó)
  const isJvVote = (v) => {
    const mt = String(v.member_type || '').toLowerCase().trim();
    const tp = String(v.tipo_participante || '').toUpperCase().trim();
    const role = String(v.role || '').toUpperCase();
    return mt === 'junta_vigilancia' || tp === 'JUNTA_DE_VIGILANCIA' || role.includes('VIGILANCIA');
  };
  const jvVote = votes.find(isJvVote);
  const clientName = client?.name || 'ASOCOLCI';

  const canGenerateReports = user?.role === 'authorized' || user?.role === 'admin_master';
  const canGeneratePdf = canGenerateReports && totalVotes > 0;

  // TEST-M1: si no hay votos, no calcular resultado (evita "undefined" y "RECHAZADA" con 0 votos)
  const noVotes = !totalVotes || totalVotes === 0;

  // VOT-LOGICA-MULTIPLE: para votaciones múltiples, el ganador es la opción con más votos
  const isMultiple = voting?.type === 'multiple';
  const winnerOption = isMultiple && !noVotes && voteResults.length > 0
    ? voteResults.reduce((best, cur) => (parseInt(cur.votes) || 0) > (parseInt(best.votes) || 0) ? cur : best, voteResults[0])
    : null;
  const isTie = isMultiple && winnerOption && voteResults.filter(r => (parseInt(r.votes) || 0) === (parseInt(winnerOption.votes) || 0)).length > 1;

  // Para votación ordinaria: mayoría dinámica = floor(emitidos/2)+1 (solo si hay votos)
  const ordinariaMajority = (!isMultiple && !noVotes) ? Math.floor(totalVotes / 2) + 1 : null;
  const affirmativeOptions = ['a favor', 'sí', 'si', 'yes', 'aprobado'];
  const affirmativeVotes = !isMultiple
    ? voteResults.filter(r => affirmativeOptions.includes((r.option || '').toLowerCase()))
        .reduce((s, r) => s + (parseInt(r.votes) || 0), 0)
    : 0;
  const ordinariaApproved = !isMultiple && ordinariaMajority !== null && affirmativeVotes >= ordinariaMajority;

  return (
    <div className="voting-results">
      <div className="container">
        <button onClick={() => navigate(`/meetings/${meetingId}`)} className="btn-back">
          ← Volver a Reunión
        </button>

        <div className="results-header">
          <h1>{language === 'es' ? 'Resultados de Votación' : 'Voting Results'}</h1>
          <h2>{voting.title}</h2>
        </div>

        {/* TEST-M1: banner sin votos */}
        {noVotes && (
          <div style={{ background: '#fef9c3', border: '1px solid #fde047', borderRadius: '8px', padding: '14px 20px', marginBottom: '16px', color: '#854d0e', fontWeight: 600 }}>
            ⏳ {language === 'es' ? 'Sin votos registrados aún — los resultados aparecerán aquí cuando los participantes voten.' : 'No votes recorded yet — results will appear here once participants vote.'}
          </div>
        )}

        <div className="results-summary">
          <div className="summary-card">
            <div className="summary-value">{totalVotes}</div>
            <div className="summary-label">{language === 'es' ? 'Total de Votos' : 'Total Votes'}</div>
          </div>
          {/* VOT-LOGICA-MULTIPLE: resultado diferenciado por tipo */}
          {isMultiple ? (
            winnerOption && (
              <div className={`summary-card ${isTie ? '' : 'approved'}`}>
                <div className="summary-value" style={{ fontSize: '18px' }}>
                  {isTie ? '⚖️' : '🏆'}
                </div>
                <div className="summary-label">
                  {isTie
                    ? (language === 'es' ? 'EMPATE' : 'TIE')
                    : `GANADOR: ${winnerOption.option} (${winnerOption.votes} votos)`}
                </div>
              </div>
            )
          ) : (
            <>
              {ordinariaMajority !== null && (
                <div className="summary-card">
                  <div className="summary-value">{ordinariaMajority}</div>
                  <div className="summary-label">{language === 'es' ? 'Mayoría Requerida' : 'Required Majority'}</div>
                </div>
              )}
              <div className={`summary-card ${ordinariaApproved ? 'approved' : 'rejected'}`}>
                <div className="summary-value">{ordinariaApproved ? '✓' : '✗'}</div>
                <div className="summary-label">
                  {ordinariaApproved
                    ? (language === 'es' ? 'APROBADA' : 'APPROVED')
                    : (language === 'es' ? 'RECHAZADA' : 'REJECTED')}
                </div>
              </div>
            </>
          )}
        </div>

        {/* Bloque de detalle del resultado — oculto si no hay votos (TEST-M1) */}
        {!noVotes && isMultiple ? (
          <div className={`majority-validation ${isTie ? '' : 'approved'}`}>
            <h3>{language === 'es' ? 'Resultado — Selección Múltiple' : 'Result — Multiple Choice'}</h3>
            {isTie ? (
              <div className="validation-result">
                {language === 'es'
                  ? `Empate entre opciones con ${winnerOption.votes} votos. Se requiere desempate.`
                  : `Tie between options with ${winnerOption.votes} votes. Tiebreaker required.`}
              </div>
            ) : (
              <div className="validation-result approved">
                {language === 'es'
                  ? `GANADOR: ${winnerOption?.option} con ${winnerOption?.votes} votos (${totalVotes > 0 ? ((parseInt(winnerOption?.votes)||0)*100/totalVotes).toFixed(1) : 0}% del total).`
                  : `WINNER: ${winnerOption?.option} with ${winnerOption?.votes} votes (${totalVotes > 0 ? ((parseInt(winnerOption?.votes)||0)*100/totalVotes).toFixed(1) : 0}% of total).`}
              </div>
            )}
          </div>
        ) : (
          ordinariaMajority !== null && (
            <div className={`majority-validation ${ordinariaApproved ? 'approved' : 'rejected'}`}>
              <h3>{language === 'es' ? 'Resultado — Votación Ordinaria' : 'Result — Ordinary Vote'}</h3>
              <div className="validation-details">
                <div className="validation-item">
                  <span className="label">{language === 'es' ? 'Votos A favor:' : 'Votes In favor:'}</span>
                  <span className="value">{affirmativeVotes}</span>
                </div>
                <div className="validation-item">
                  <span className="label">{language === 'es' ? 'Mayoría requerida:' : 'Required majority:'}</span>
                  <span className="value">{ordinariaMajority}</span>
                </div>
                <div className="validation-item">
                  <span className="label">{language === 'es' ? 'Total emitidos:' : 'Total cast:'}</span>
                  <span className="value">{totalVotes}</span>
                </div>
              </div>
              <div className={`validation-result ${ordinariaApproved ? 'approved' : 'rejected'}`}>
                {ordinariaApproved
                  ? (language === 'es' ? `APROBADA — ${affirmativeVotes} votos a favor (mínimo requerido: ${ordinariaMajority})` : `APPROVED — ${affirmativeVotes} votes in favor (minimum required: ${ordinariaMajority})`)
                  : (language === 'es' ? `RECHAZADA — ${affirmativeVotes} votos a favor (mínimo requerido: ${ordinariaMajority})` : `REJECTED — ${affirmativeVotes} votes in favor (minimum required: ${ordinariaMajority})`)}
              </div>
            </div>
          )
        )}

        <div className="results-chart">
          <h3>{language === 'es' ? 'Distribución de Votos' : 'Vote Distribution'}</h3>
          <div className="chart-container">
            {voteResults.map((result, index) => {
              const percentage = totalVotes > 0 ? (result.votes / totalVotes) * 100 : 0;
              return (
                <div key={index} className="chart-item">
                  <div className="chart-header">
                    <span className="chart-option">{result.option}</span>
                    <span className="chart-count">{result.votes} votos ({percentage.toFixed(1)}%)</span>
                  </div>
                  <div className="chart-bar-container">
                    <div 
                      className="chart-bar"
                      style={{ 
                        width: `${percentage}%`,
                        backgroundColor: index === 0 ? 'var(--success)' : index === 1 ? 'var(--danger)' : 'var(--warning)'
                      }}
                    >
                      <span className="chart-percentage">{percentage.toFixed(1)}%</span>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* §9 JV — Voto institucional de la Junta de Vigilancia */}
        {jvVote && (
          <div style={{
            background: 'rgba(167,139,250,0.08)', border: '1px solid rgba(167,139,250,0.4)',
            borderRadius: '8px', padding: '14px 20px', margin: '12px 0',
            display: 'flex', alignItems: 'center', gap: '14px', flexWrap: 'wrap'
          }}>
            <span style={{ fontSize: '20px' }}>⚖️</span>
            <div>
              <div style={{ fontWeight: 700, color: '#7c3aed', fontSize: '14px' }}>
                {language === 'es'
                  ? `Representante JV (${clientName}): ${jvVote.member_name}`
                  : `JV Representative (${clientName}): ${jvVote.member_name}`}
              </div>
              <div style={{ fontSize: '13px', color: 'var(--text-secondary)', marginTop: '3px' }}>
                {language === 'es'
                  ? `Sentido del voto institucional: ${jvVote.option}`
                  : `Institutional vote: ${jvVote.option}`}
              </div>
            </div>
            <span style={{
              marginLeft: 'auto', background: 'rgba(124,58,237,0.15)', color: '#7c3aed',
              borderRadius: '6px', padding: '4px 12px', fontWeight: 700, fontSize: '13px'
            }}>
              {jvVote.option}
            </span>
          </div>
        )}

        <div className="votes-detail">
          <h3>{language === 'es' ? 'Detalle de Votos' : 'Vote Details'}</h3>
          <div className="votes-table">
            <div className="table-header">
              <div>{language === 'es' ? 'Miembro' : 'Member'}</div>
              <div>{language === 'es' ? 'Rol' : 'Role'}</div>
              <div>{language === 'es' ? 'Voto' : 'Vote'}</div>
            </div>
            {votes.map(vote => (
              <div key={vote.id} className="table-row">
                <div><strong>{vote.member_name}</strong></div>
                <div>{vote.role}</div>
                <div>
                  <span className={`vote-badge option-${vote.option.toLowerCase()}`}>
                    {vote.option}
                  </span>
                </div>
              </div>
            ))}
          </div>
        </div>

        <div className="results-actions">
          {canGenerateReports && (
            <button
              className="btn btn-primary"
              onClick={generatePDF}
              disabled={!canGeneratePdf}
              title={
                !canGeneratePdf
                  ? (language === 'es'
                      ? 'No se puede generar PDF sin votos emitidos'
                      : 'Cannot generate PDF without votes cast')
                  : undefined
              }
              style={!canGeneratePdf ? { opacity: 0.6, cursor: 'not-allowed' } : undefined}
            >
              📄 {language === 'es' ? 'Generar PDF' : 'Generate PDF'}
            </button>
          )}
          <button className="btn btn-secondary" onClick={() => window.print()}>
            🖨️ {language === 'es' ? 'Imprimir' : 'Print'}
          </button>
          <button className="btn btn-secondary" onClick={() => navigate(`/meetings/${meetingId}`)}>
            {language === 'es' ? '← Volver a Reunión' : '← Back to Meeting'}
          </button>
        </div>
      </div>
    </div>
  );
};

export default VotingResults;

