import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';
import { useLanguage } from '../../context/LanguageContext';
import { votingService } from '../../services/votingService';
import { meetingService } from '../../services/meetingService';
import jsPDF from 'jspdf';
import './VotingResults.css';

const VotingResults = () => {
  const { meetingId, votingId } = useParams();
  const navigate = useNavigate();
  const { user, client } = useAuth();
  const { t, language } = useLanguage();
  const [results, setResults] = useState(null);
  const [meeting, setMeeting] = useState(null);
  const [quorumDetail, setQuorumDetail] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadResults();
  }, [votingId]);

  const loadResults = async () => {
    try {
      const [resultsRes, meetingRes, quorumRes] = await Promise.allSettled([
        votingService.getResults(votingId),
        meetingService.getById(meetingId),
        meetingService.getQuorumDetail(meetingId)
      ]);
      if (resultsRes.status === 'fulfilled') setResults(resultsRes.value.data);
      if (meetingRes.status === 'fulfilled') setMeeting(meetingRes.value.data);
      if (quorumRes.status === 'fulfilled') setQuorumDetail(quorumRes.value.data);
    } catch (error) {
      console.error('Error loading results:', error);
    } finally {
      setLoading(false);
    }
  };

  // ─── helpers PDF ──────────────────────────────────────────────────────────

  const checkPage = (doc, yPos, needed = 20) => {
    if (yPos > doc.internal.pageSize.getHeight() - needed) {
      doc.addPage();
      return 28;
    }
    return yPos;
  };

  const sectionTitle = (doc, text, y, pageWidth) => {
    doc.setFillColor(30, 41, 59);
    doc.rect(14, y - 5, pageWidth - 28, 9, 'F');
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(255, 255, 255);
    doc.text(text.toUpperCase(), 17, y);
    doc.setTextColor(0, 0, 0);
    return y + 10;
  };

  const kv = (doc, label, value, y, margin, col2 = margin + 52) => {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.text(`${label}:`, margin, y);
    doc.setFont('helvetica', 'normal');
    const lines = doc.splitTextToSize(String(value ?? '-'), 120);
    doc.text(lines, col2, y);
    return y + 6 * lines.length;
  };

  const tableRow = (doc, cols, y, margin, widths, bold = false) => {
    doc.setFont('helvetica', bold ? 'bold' : 'normal');
    doc.setFontSize(8);
    let x = margin;
    cols.forEach((txt, i) => {
      const lines = doc.splitTextToSize(String(txt ?? '-'), widths[i] - 2);
      doc.text(lines, x + 1, y);
      x += widths[i];
    });
    const rowH = 6;
    return y + rowH;
  };

  const tableHeader = (doc, cols, y, margin, widths, pageWidth) => {
    doc.setFillColor(71, 85, 105);
    doc.rect(margin, y - 4, pageWidth - 28, 7, 'F');
    doc.setTextColor(255, 255, 255);
    let x = margin;
    doc.setFontSize(7.5);
    doc.setFont('helvetica', 'bold');
    cols.forEach((h, i) => { doc.text(h, x + 1, y); x += widths[i]; });
    doc.setTextColor(0, 0, 0);
    return y + 7;
  };

  // ─── branding por página ──────────────────────────────────────────────────

  const addPdfBranding = (doc, voting) => {
    const pageCount = doc.getNumberOfPages();
    const clientName = (client?.name || 'ASOCOLCI').toUpperCase();
    const generatedAt = new Date().toLocaleString(language === 'es' ? 'es-ES' : 'en-US');

    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();

      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(0, 0, 0);
      doc.text(clientName, 14, 9);
      doc.setFont('helvetica', 'normal');
      doc.text(`${voting?.title || '-'} · ${language === 'es' ? 'Reporte de Votación' : 'Voting Report'}`, 14, 14);
      doc.setLineWidth(0.3);
      doc.line(14, 18, pageWidth - 14, 18);

      doc.setLineWidth(0.3);
      doc.line(14, pageHeight - 14, pageWidth - 14, pageHeight - 14);
      doc.setFontSize(7.5);
      doc.setFont('helvetica', 'italic');
      doc.text(
        `${language === 'es' ? 'Generado por' : 'Generated by'} BOARD QUORUM · ${generatedAt}`,
        14, pageHeight - 8
      );
      doc.text(
        `${language === 'es' ? 'Pág' : 'Page'} ${i}/${pageCount}`,
        pageWidth - 28, pageHeight - 8
      );
    }
  };

  // ─── PDF principal ────────────────────────────────────────────────────────

  const generatePDF = () => {
    if (!results) return;

    const { voting, results: voteResults, votes, totalVotes, majority, majorityValidation } = results;
    if (!totalVotes || totalVotes === 0) {
      alert(language === 'es'
        ? 'No se puede generar el PDF porque no hay votos emitidos.'
        : 'Cannot generate PDF because there are no votes cast.');
      return;
    }

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 14;
    let y = 24;
    const LH = 6.5;
    const clientName = (client?.name || 'ASOCOLCI').toUpperCase();

    const isJvVoteRow = (v) => {
      const mt = String(v.member_type || '').toLowerCase().trim();
      const tp = String(v.tipo_participante || '').toUpperCase().trim();
      const role = String(v.role || '').toUpperCase();
      return mt === 'junta_vigilancia' || tp === 'JUNTA_DE_VIGILANCIA' || role.includes('VIGILANCIA');
    };

    const jvVotePdf = votes.find(isJvVoteRow);

    const isMultiple = voting?.type === 'multiple';
    const affirmativeOptions = ['a favor', 'sí', 'si', 'yes', 'aprobado'];
    const affirmativeVotes = !isMultiple
      ? voteResults.filter(r => affirmativeOptions.includes((r.option || '').toLowerCase()))
          .reduce((s, r) => s + (parseInt(r.votes) || 0), 0)
      : 0;
    const baseVotes = quorumDetail?.computable_votes || totalVotes;
    const requiredMajority = Math.floor(baseVotes / 2) + 1;
    const approved = !isMultiple ? affirmativeVotes >= requiredMajority : false;

    const meetingTypeLabel = {
      junta_directiva: language === 'es' ? 'Junta Directiva' : 'Board of Directors',
      asamblea: language === 'es' ? 'Asamblea General' : 'General Assembly',
      comite: language === 'es' ? 'Comité' : 'Committee',
    }[meeting?.type] || (meeting?.type || '-');

    const meetingDate = meeting?.date
      ? new Date(meeting.date).toLocaleDateString(language === 'es' ? 'es-ES' : 'en-US', {
          year: 'numeric', month: 'long', day: 'numeric'
        })
      : '-';

    const docId = `BQ-${Date.now().toString(36).toUpperCase()}`;

    // ── 4.1 ENCABEZADO INSTITUCIONAL ───────────────────────────────────────
    y = sectionTitle(doc, language === 'es' ? '4.1 Encabezado institucional' : '4.1 Institutional Header', y, pageWidth);
    y = kv(doc, language === 'es' ? 'Organización' : 'Organization', clientName, y, margin);
    y = kv(doc, language === 'es' ? 'Tipo de órgano' : 'Organ type', meetingTypeLabel, y, margin);
    y = kv(doc, language === 'es' ? 'Sesión' : 'Session', meeting?.title || '-', y, margin);
    y = kv(doc, language === 'es' ? 'Fecha' : 'Date', meetingDate, y, margin);
    y = kv(doc, language === 'es' ? 'ID Reunión / ID Votación' : 'Meeting ID / Voting ID',
      `${meetingId} / ${votingId}`, y, margin);
    y = kv(doc, language === 'es' ? 'Asunto votado' : 'Matter voted', voting.title, y, margin);
    y += 4;

    // ── 4.2 BLOQUE DE QUÓRUM ───────────────────────────────────────────────
    y = checkPage(doc, y, 40);
    y = sectionTitle(doc, language === 'es' ? '4.2 Bloque de quórum' : '4.2 Quorum Block', y, pageWidth);
    if (quorumDetail) {
      y = kv(doc, language === 'es' ? 'Total asistentes' : 'Total attendees', quorumDetail.total_present, y, margin);
      y = kv(doc, language === 'es' ? 'Asistentes computables' : 'Computable attendees', quorumDetail.computable_votes, y, margin);
      y = kv(doc, language === 'es' ? 'Quórum mínimo requerido' : 'Minimum quorum required', quorumDetail.required ?? '-', y, margin);
      const qStatus = quorumDetail.quorum_met
        ? (language === 'es' ? 'CUMPLIDO ✓' : 'MET ✓')
        : (language === 'es' ? 'NO CUMPLIDO ✗' : 'NOT MET ✗');
      y = kv(doc, language === 'es' ? 'Resultado de quórum' : 'Quorum result', qStatus, y, margin);
      if (quorumDetail.jv_institutional_vote) {
        y = kv(doc, language === 'es' ? 'Voto institucional JV' : 'JV institutional vote',
          language === 'es' ? '1 voto (incluido en computables)' : '1 vote (included in computable)', y, margin);
      }
    } else {
      doc.setFontSize(9); doc.setFont('helvetica', 'italic');
      doc.text(language === 'es' ? 'Datos de quórum no disponibles.' : 'Quorum data not available.', margin, y);
      y += LH;
    }
    y += 4;

    // ── 4.3 BASE DE VOTANTES ───────────────────────────────────────────────
    y = checkPage(doc, y, 50);
    y = sectionTitle(doc, language === 'es' ? '4.3 Base de votantes (eligible_voters_set)' : '4.3 Voter Base', y, pageWidth);
    if (quorumDetail?.breakdown?.length) {
      const bCols = language === 'es'
        ? ['Nombre', 'Rol', 'Tipo', 'Puede votar', 'Justificación']
        : ['Name', 'Role', 'Type', 'Can vote', 'Justification'];
      const bW = [52, 38, 22, 22, 48];
      y = tableHeader(doc, bCols, y, margin, bW, pageWidth);

      quorumDetail.breakdown.forEach((row, idx) => {
        y = checkPage(doc, y, 10);
        if (idx % 2 === 0) {
          doc.setFillColor(248, 250, 252);
          doc.rect(margin, y - 4, pageWidth - 28, 6, 'F');
        }
        const tipo = (() => {
          const mt = String(row.member_type || '').toLowerCase();
          if (mt === 'junta_vigilancia') return 'JV';
          if (mt === 'suplente') return language === 'es' ? 'Suplente' : 'Substitute';
          return language === 'es' ? 'Principal' : 'Principal';
        })();
        const puedeVotar = row.counts
          ? (language === 'es' ? 'Sí ✓' : 'Yes ✓')
          : row.reason === 'JV_VOTO_INSTITUCIONAL'
            ? 'JV (1)'
            : (language === 'es' ? 'No ✗' : 'No ✗');
        y = tableRow(doc, [row.name, row.role || '-', tipo, puedeVotar, row.reason_label || row.reason], y, margin, bW);
      });
    } else {
      doc.setFontSize(9); doc.setFont('helvetica', 'italic');
      doc.text(language === 'es' ? 'Datos de asistencia no disponibles.' : 'Attendance data not available.', margin, y);
      y += LH;
    }
    y += 4;

    // ── 4.4 REGLAS DE VOTACIÓN ─────────────────────────────────────────────
    y = checkPage(doc, y, 40);
    y = sectionTitle(doc, language === 'es' ? '4.4 Reglas de votación' : '4.4 Voting Rules', y, pageWidth);
    y = kv(doc, language === 'es' ? 'Tipo de votación' : 'Voting type',
      isMultiple ? (language === 'es' ? 'Selección múltiple' : 'Multiple choice') : (language === 'es' ? 'Ordinaria (A favor / En contra / Abstención)' : 'Ordinary (In favor / Against / Abstention)'),
      y, margin);
    y = kv(doc, language === 'es' ? 'Base de votos válidos' : 'Valid vote base', `${baseVotes} ${language === 'es' ? 'votantes computables' : 'computable voters'}`, y, margin);
    if (!isMultiple) {
      y = kv(doc, language === 'es' ? 'Mayoría requerida' : 'Required majority', `${requiredMajority} ${language === 'es' ? 'votos (mayoría simple)' : 'votes (simple majority)'}`, y, margin);
      y = kv(doc, language === 'es' ? 'Fórmula' : 'Formula', `floor(${baseVotes}/2) + 1 = ${requiredMajority}`, y, margin);
    }
    y += 4;

    // ── 4.5 RESULTADO NUMÉRICO ─────────────────────────────────────────────
    y = checkPage(doc, y, 50);
    y = sectionTitle(doc, language === 'es' ? '4.5 Resultado numérico' : '4.5 Numerical Result', y, pageWidth);
    y = kv(doc, language === 'es' ? 'Total votos emitidos' : 'Total votes cast', totalVotes, y, margin);
    y = kv(doc, language === 'es' ? 'Votos válidos' : 'Valid votes', totalVotes, y, margin);
    voteResults.forEach(r => {
      const pct = totalVotes > 0 ? ((r.votes / totalVotes) * 100).toFixed(1) : '0.0';
      y = kv(doc, r.option, `${r.votes} (${pct}%)`, y, margin);
    });
    if (!isMultiple) {
      y = kv(doc, language === 'es' ? 'Mayoría requerida' : 'Required majority', requiredMajority, y, margin);
      y = kv(doc, language === 'es' ? 'Votos a favor' : 'Votes in favor', affirmativeVotes, y, margin);
    }
    y += 4;

    // ── 4.6 RESULTADO JURÍDICO ─────────────────────────────────────────────
    y = checkPage(doc, y, 30);
    y = sectionTitle(doc, language === 'es' ? '4.6 Resultado jurídico' : '4.6 Legal Result', y, pageWidth);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    const resultColor = isMultiple
      ? [30, 41, 59]
      : approved ? [5, 150, 105] : [220, 38, 38];
    doc.setTextColor(...resultColor);

    let legalText;
    if (isMultiple) {
      const winner = voteResults.reduce((b, c) => (parseInt(c.votes)||0) > (parseInt(b.votes)||0) ? c : b, voteResults[0]);
      legalText = language === 'es'
        ? `La opción "${winner.option}" obtiene ${winner.votes} votos, siendo la más votada en esta votación de selección múltiple.`
        : `Option "${winner.option}" obtains ${winner.votes} votes, being the most voted in this multiple-choice voting.`;
    } else if (approved) {
      legalText = language === 'es'
        ? `La proposición alcanza la mayoría requerida (${affirmativeVotes} votos a favor sobre ${requiredMajority} requeridos), por lo cual se declara APROBADA.`
        : `The proposition reaches the required majority (${affirmativeVotes} votes in favor vs. ${requiredMajority} required), therefore it is declared APPROVED.`;
    } else {
      legalText = language === 'es'
        ? `La proposición no alcanza la mayoría requerida (${affirmativeVotes} votos a favor, se requerían ${requiredMajority}), por lo cual se declara RECHAZADA.`
        : `The proposition does not reach the required majority (${affirmativeVotes} votes in favor, ${requiredMajority} required), therefore it is declared REJECTED.`;
    }
    const legalLines = doc.splitTextToSize(legalText, pageWidth - 28);
    doc.text(legalLines, margin, y);
    doc.setTextColor(0, 0, 0);
    y += LH * legalLines.length + 4;

    // ── 4.7 DETALLE DE VOTACIÓN ────────────────────────────────────────────
    y = checkPage(doc, y, 40);
    y = sectionTitle(doc, language === 'es' ? '4.7 Detalle de votación' : '4.7 Voting Detail', y, pageWidth);
    const dCols = language === 'es'
      ? ['Nombre', 'Rol', 'Tipo de voto', 'Sentido']
      : ['Name', 'Role', 'Vote type', 'Direction'];
    const dW = [58, 42, 38, 44];
    y = tableHeader(doc, dCols, y, margin, dW, pageWidth);

    votes.forEach((vote, idx) => {
      y = checkPage(doc, y, 10);
      if (idx % 2 === 0) {
        doc.setFillColor(248, 250, 252);
        doc.rect(margin, y - 4, pageWidth - 28, 6, 'F');
      }
      const voteType = isJvVoteRow(vote)
        ? (language === 'es' ? 'Institucional JV' : 'JV Institutional')
        : String(vote.member_type || '').toLowerCase() === 'suplente'
          ? (language === 'es' ? 'Suplente actuando' : 'Acting substitute')
          : (language === 'es' ? 'Principal' : 'Principal');
      y = tableRow(doc, [vote.member_name, vote.role || '-', voteType, vote.option], y, margin, dW);
    });
    y += 4;

    // ── 4.8 JUNTA DE VIGILANCIA ────────────────────────────────────────────
    if (jvVotePdf || (quorumDetail?.jv_institutional_vote)) {
      y = checkPage(doc, y, 35);
      y = sectionTitle(doc, language === 'es' ? '4.8 Junta de vigilancia' : '4.8 Oversight Board', y, pageWidth);
      const jvCount = quorumDetail?.jv_members?.length || (jvVotePdf ? 1 : 0);
      y = kv(doc, language === 'es' ? 'Miembros JV presentes' : 'JV members present', jvCount, y, margin);
      if (jvVotePdf) {
        y = kv(doc, language === 'es' ? 'Representante que votó' : 'Representative who voted', jvVotePdf.member_name, y, margin);
        y = kv(doc, language === 'es' ? 'Sentido del voto' : 'Vote direction', jvVotePdf.option, y, margin);
      }
      y = kv(doc, language === 'es' ? 'Voto único institucional' : 'Single institutional vote',
        language === 'es' ? 'Confirmado (1 voto emitido por la JV)' : 'Confirmed (1 vote cast by JV)', y, margin);
      y += 4;
    }

    // ── 4.9 VALIDACIONES AUTOMÁTICAS ──────────────────────────────────────
    y = checkPage(doc, y, 45);
    y = sectionTitle(doc, language === 'es' ? '4.9 Validaciones automáticas' : '4.9 Automatic Validations', y, pageWidth);
    const validations = language === 'es' ? [
      '✓ Solo votaron personas registradas como presentes y aprobadas en asistencia.',
      '✓ No se registraron votos de personas no asistentes (NOT_PRESENT bloqueado).',
      '✓ No se registraron votos duplicados (ALREADY_VOTED bloqueado).',
      '✓ Suplentes con principal presente fueron bloqueados (SUPLENTE_SIN_VOTO).',
      '✓ Cargos con suplente ya votado fueron bloqueados (CARGO_YA_VOTADO).',
      '✓ Roles sin derecho a voto fueron bloqueados (NO_VOTE).',
      '✓ La Junta de Vigilancia emitió un único voto institucional (JV_VOTED).',
    ] : [
      '✓ Only persons registered as present and approved in attendance were allowed to vote.',
      '✓ No votes from non-attendees were recorded (NOT_PRESENT blocked).',
      '✓ No duplicate votes were recorded (ALREADY_VOTED blocked).',
      '✓ Substitutes with present principal were blocked (SUPLENTE_SIN_VOTO).',
      '✓ Positions with already-voted substitute were blocked (CARGO_YA_VOTADO).',
      '✓ Roles without voting rights were blocked (NO_VOTE).',
      '✓ The Oversight Board cast a single institutional vote (JV_VOTED).',
    ];
    doc.setFontSize(8.5);
    doc.setFont('helvetica', 'normal');
    validations.forEach(v => {
      y = checkPage(doc, y, 8);
      doc.text(v, margin, y);
      y += LH;
    });
    y += 4;

    // ── 4.11 PIE DE AUDITORÍA ──────────────────────────────────────────────
    y = checkPage(doc, y, 35);
    y = sectionTitle(doc, language === 'es' ? '4.11 Pie de auditoría' : '4.11 Audit Footer', y, pageWidth);
    y = kv(doc, language === 'es' ? 'Fecha/hora de generación' : 'Generation date/time',
      new Date().toLocaleString(language === 'es' ? 'es-ES' : 'en-US'), y, margin);
    y = kv(doc, language === 'es' ? 'Versión del sistema' : 'System version', 'BOARD QUORUM v2.0', y, margin);
    y = kv(doc, language === 'es' ? 'Identificador único' : 'Unique identifier', docId, y, margin);
    y = kv(doc, language === 'es' ? 'Origen' : 'Origin', 'BOARD QUORUM — Plataforma de Gobernanza Corporativa', y, margin);

    addPdfBranding(doc, voting);

    const fileName = `Reporte_Votacion_${voting.title.replace(/[^a-z0-9]/gi, '_')}_${docId}.pdf`;
    doc.save(fileName);
  };

  if (loading) return <div className="loading">{language === 'es' ? 'Cargando resultados...' : 'Loading results...'}</div>;
  if (!results) return <div className="error">{language === 'es' ? 'No se pudieron cargar los resultados' : 'Could not load results'}</div>;

  const { voting, results: voteResults, votes, totalVotes, majority, majorityValidation } = results;
  const maxVotes = Math.max(...voteResults.map(r => parseInt(r.votes) || 0), 0);

  const isJvVote = (v) => {
    const mt = String(v.member_type || '').toLowerCase().trim();
    const tp = String(v.tipo_participante || '').toUpperCase().trim();
    const role = String(v.role || '').toUpperCase();
    return mt === 'junta_vigilancia' || tp === 'JUNTA_DE_VIGILANCIA' || role.includes('VIGILANCIA');
  };
  const jvVote = votes.find(isJvVote);
  const clientName = client?.name || 'ASOCOLCI';

  const canGenerateReports = user?.role === 'authorized' || user?.role === 'admin_master';
  const canGeneratePdf = canGenerateReports && totalVotes > 0;

  const noVotes = !totalVotes || totalVotes === 0;

  const isMultiple = voting?.type === 'multiple';
  const winnerOption = isMultiple && !noVotes && voteResults.length > 0
    ? voteResults.reduce((best, cur) => (parseInt(cur.votes) || 0) > (parseInt(best.votes) || 0) ? cur : best, voteResults[0])
    : null;
  const isTie = isMultiple && winnerOption && voteResults.filter(r => (parseInt(r.votes) || 0) === (parseInt(winnerOption.votes) || 0)).length > 1;

  const ordinariaMajority = (!isMultiple && !noVotes) ? Math.floor(totalVotes / 2) + 1 : null;
  const affirmativeOptions = ['a favor', 'sí', 'si', 'yes', 'aprobado'];
  const affirmativeVotes = !isMultiple
    ? voteResults.filter(r => affirmativeOptions.includes((r.option || '').toLowerCase()))
        .reduce((s, r) => s + (parseInt(r.votes) || 0), 0)
    : 0;
  const ordinariaApproved = !isMultiple && ordinariaMajority !== null && affirmativeVotes >= ordinariaMajority;

  return (
    <div className="voting-results">
      <div className="container">
        <button onClick={() => navigate(`/meetings/${meetingId}`)} className="btn-back">
          ← Volver a Reunión
        </button>

        <div className="results-header">
          <h1>{language === 'es' ? 'Resultados de Votación' : 'Voting Results'}</h1>
          <h2>{voting.title}</h2>
        </div>

        {noVotes && (
          <div style={{ background: '#fef9c3', border: '1px solid #fde047', borderRadius: '8px', padding: '14px 20px', marginBottom: '16px', color: '#854d0e', fontWeight: 600 }}>
            ⏳ {language === 'es' ? 'Sin votos registrados aún — los resultados aparecerán aquí cuando los participantes voten.' : 'No votes recorded yet — results will appear here once participants vote.'}
          </div>
        )}

        <div className="results-summary">
          <div className="summary-card">
            <div className="summary-value">{totalVotes}</div>
            <div className="summary-label">{language === 'es' ? 'Total de Votos' : 'Total Votes'}</div>
          </div>
          {isMultiple ? (
            winnerOption && (
              <div className={`summary-card ${isTie ? '' : 'approved'}`}>
                <div className="summary-value" style={{ fontSize: '18px' }}>
                  {isTie ? '⚖️' : '🏆'}
                </div>
                <div className="summary-label">
                  {isTie
                    ? (language === 'es' ? 'EMPATE' : 'TIE')
                    : `GANADOR: ${winnerOption.option} (${winnerOption.votes} votos)`}
                </div>
              </div>
            )
          ) : (
            <>
              {ordinariaMajority !== null && (
                <div className="summary-card">
                  <div className="summary-value">{ordinariaMajority}</div>
                  <div className="summary-label">{language === 'es' ? 'Mayoría Requerida' : 'Required Majority'}</div>
                </div>
              )}
              <div className={`summary-card ${ordinariaApproved ? 'approved' : 'rejected'}`}>
                <div className="summary-value">{ordinariaApproved ? '✓' : '✗'}</div>
                <div className="summary-label">
                  {ordinariaApproved
                    ? (language === 'es' ? 'APROBADA' : 'APPROVED')
                    : (language === 'es' ? 'RECHAZADA' : 'REJECTED')}
                </div>
              </div>
            </>
          )}
        </div>

        {!noVotes && isMultiple ? (
          <div className={`majority-validation ${isTie ? '' : 'approved'}`}>
            <h3>{language === 'es' ? 'Resultado — Selección Múltiple' : 'Result — Multiple Choice'}</h3>
            {isTie ? (
              <div className="validation-result">
                {language === 'es'
                  ? `Empate entre opciones con ${winnerOption.votes} votos. Se requiere desempate.`
                  : `Tie between options with ${winnerOption.votes} votes. Tiebreaker required.`}
              </div>
            ) : (
              <div className="validation-result approved">
                {language === 'es'
                  ? `GANADOR: ${winnerOption?.option} con ${winnerOption?.votes} votos (${totalVotes > 0 ? ((parseInt(winnerOption?.votes)||0)*100/totalVotes).toFixed(1) : 0}% del total).`
                  : `WINNER: ${winnerOption?.option} with ${winnerOption?.votes} votes (${totalVotes > 0 ? ((parseInt(winnerOption?.votes)||0)*100/totalVotes).toFixed(1) : 0}% of total).`}
              </div>
            )}
          </div>
        ) : (
          ordinariaMajority !== null && (
            <div className={`majority-validation ${ordinariaApproved ? 'approved' : 'rejected'}`}>
              <h3>{language === 'es' ? 'Resultado — Votación Ordinaria' : 'Result — Ordinary Vote'}</h3>
              <div className="validation-details">
                <div className="validation-item">
                  <span className="label">{language === 'es' ? 'Votos A favor:' : 'Votes In favor:'}</span>
                  <span className="value">{affirmativeVotes}</span>
                </div>
                <div className="validation-item">
                  <span className="label">{language === 'es' ? 'Mayoría requerida:' : 'Required majority:'}</span>
                  <span className="value">{ordinariaMajority}</span>
                </div>
                <div className="validation-item">
                  <span className="label">{language === 'es' ? 'Total emitidos:' : 'Total cast:'}</span>
                  <span className="value">{totalVotes}</span>
                </div>
              </div>
              <div className={`validation-result ${ordinariaApproved ? 'approved' : 'rejected'}`}>
                {ordinariaApproved
                  ? (language === 'es' ? `APROBADA — ${affirmativeVotes} votos a favor (mínimo requerido: ${ordinariaMajority})` : `APPROVED — ${affirmativeVotes} votes in favor (minimum required: ${ordinariaMajority})`)
                  : (language === 'es' ? `RECHAZADA — ${affirmativeVotes} votos a favor (mínimo requerido: ${ordinariaMajority})` : `REJECTED — ${affirmativeVotes} votes in favor (minimum required: ${ordinariaMajority})`)}
              </div>
            </div>
          )
        )}

        <div className="results-chart">
          <h3>{language === 'es' ? 'Distribución de Votos' : 'Vote Distribution'}</h3>
          <div className="chart-container">
            {voteResults.map((result, index) => {
              const percentage = totalVotes > 0 ? (result.votes / totalVotes) * 100 : 0;
              return (
                <div key={index} className="chart-item">
                  <div className="chart-header">
                    <span className="chart-option">{result.option}</span>
                    <span className="chart-count">{result.votes} votos ({percentage.toFixed(1)}%)</span>
                  </div>
                  <div className="chart-bar-container">
                    <div
                      className="chart-bar"
                      style={{
                        width: `${percentage}%`,
                        backgroundColor: index === 0 ? 'var(--success)' : index === 1 ? 'var(--danger)' : 'var(--warning)'
                      }}
                    >
                      <span className="chart-percentage">{percentage.toFixed(1)}%</span>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {jvVote && (
          <div style={{
            background: 'rgba(167,139,250,0.08)', border: '1px solid rgba(167,139,250,0.4)',
            borderRadius: '8px', padding: '14px 20px', margin: '12px 0',
            display: 'flex', alignItems: 'center', gap: '14px', flexWrap: 'wrap'
          }}>
            <span style={{ fontSize: '20px' }}>⚖️</span>
            <div>
              <div style={{ fontWeight: 700, color: '#7c3aed', fontSize: '14px' }}>
                {language === 'es'
                  ? `Representante JV (${clientName}): ${jvVote.member_name}`
                  : `JV Representative (${clientName}): ${jvVote.member_name}`}
              </div>
              <div style={{ fontSize: '13px', color: 'var(--text-secondary)', marginTop: '3px' }}>
                {language === 'es'
                  ? `Sentido del voto institucional: ${jvVote.option}`
                  : `Institutional vote: ${jvVote.option}`}
              </div>
            </div>
            <span style={{
              marginLeft: 'auto', background: 'rgba(124,58,237,0.15)', color: '#7c3aed',
              borderRadius: '6px', padding: '4px 12px', fontWeight: 700, fontSize: '13px'
            }}>
              {jvVote.option}
            </span>
          </div>
        )}

        <div className="votes-detail">
          <h3>{language === 'es' ? 'Detalle de Votos' : 'Vote Details'}</h3>
          <div className="votes-table">
            <div className="table-header">
              <div>{language === 'es' ? 'Miembro' : 'Member'}</div>
              <div>{language === 'es' ? 'Rol' : 'Role'}</div>
              <div>{language === 'es' ? 'Voto' : 'Vote'}</div>
            </div>
            {votes.map(vote => (
              <div key={vote.id} className="table-row">
                <div><strong>{vote.member_name}</strong></div>
                <div>{vote.role}</div>
                <div>
                  <span className={`vote-badge option-${vote.option.toLowerCase()}`}>
                    {vote.option}
                  </span>
                </div>
              </div>
            ))}
          </div>
        </div>

        <div className="results-actions">
          {canGenerateReports && (
            <button
              className="btn btn-primary"
              onClick={generatePDF}
              disabled={!canGeneratePdf}
              title={
                !canGeneratePdf
                  ? (language === 'es'
                      ? 'No se puede generar PDF sin votos emitidos'
                      : 'Cannot generate PDF without votes cast')
                  : undefined
              }
              style={!canGeneratePdf ? { opacity: 0.6, cursor: 'not-allowed' } : undefined}
            >
              📄 {language === 'es' ? 'Generar PDF' : 'Generate PDF'}
            </button>
          )}
          <button className="btn btn-secondary" onClick={() => window.print()}>
            🖨️ {language === 'es' ? 'Imprimir' : 'Print'}
          </button>
          <button className="btn btn-secondary" onClick={() => navigate(`/meetings/${meetingId}`)}>
            {language === 'es' ? '← Volver a Reunión' : '← Back to Meeting'}
          </button>
        </div>
      </div>
    </div>
  );
};

export default VotingResults;
