-- ============================================
-- SQL PARA INSERTAR 26 MIEMBROS DE ASOCOLCI
-- ============================================
-- LISTO PARA COPIAR Y PEGAR EN XAMPP
-- Solo reemplaza REEMPLAZA_NUM_DOC_X y REEMPLAZA_NOMBRE_X con los datos reales
-- ============================================

SET @client_id = (SELECT id FROM clients WHERE subdomain = 'asocolci' LIMIT 1);

INSERT INTO members (client_id, tipo_documento, numero_documento, name, email, rol_organico, position, role, tipo_participante, rol_en_votacion, cuenta_quorum, puede_votar, active, created_at) VALUES
(@client_id, 'C.C.', 'REEMPLAZA_NUM_DOC_1', 'REEMPLAZA_NOMBRE_1', NULL, 'PRESIDENCIA', 'PRESIDENTE', 'member', 'PRINCIPAL', 'PRINCIPAL', 1, 1, 1, NOW()),
(@client_id, 'C.C.', 'REEMPLAZA_NUM_DOC_2', 'REEMPLAZA_NOMBRE_2', NULL, 'VICE PRESIDENCIA', 'VICEPRESIDENTE', 'member', 'PRINCIPAL', 'PRINCIPAL', 1, 1, 1, NOW()),
(@client_id, 'C.C.', 'REEMPLAZA_NUM_DOC_3', 'REEMPLAZA_NOMBRE_3', NULL, 'SECRETARIA', 'SECRETARIO', 'member', 'PRINCIPAL', 'PRINCIPAL', 1, 1, 1, NOW()),
(@client_id, 'C.C.', 'REEMPLAZA_NUM_DOC_4', 'REEMPLAZA_NOMBRE_4', NULL, 'SECRETARIA', 'SUPLENTE SECRETARIA', 'member', 'SUPLENTE', 'SUPLENTE_ACTUANDO', 1, 1, 1, NOW()),
(@client_id, 'C.C.', 'REEMPLAZA_NUM_DOC_5', 'REEMPLAZA_NOMBRE_5', NULL, 'TESORERIA', 'TESORERO PRINCIPAL', 'member', 'PRINCIPAL', 'PRINCIPAL', 1, 1, 1, NOW()),
(@client_id, 'C.C.', 'REEMPLAZA_NUM_DOC_6', 'REEMPLAZA_NOMBRE_6', NULL, 'VOCALES NRO.1', 'VOCAL PRINCIPAL', 'member', 'PRINCIPAL', 'PRINCIPAL', 1, 1, 1, NOW()),
(@client_id, 'C.C.', 'REEMPLAZA_NUM_DOC_7', 'REEMPLAZA_NOMBRE_7', NULL, 'VOCALES NRO.1', 'VOCAL PRINCIPAL', 'member', 'PRINCIPAL', 'PRINCIPAL', 1, 1, 1, NOW()),
(@client_id, 'C.C.', 'REEMPLAZA_NUM_DOC_8', 'REEMPLAZA_NOMBRE_8', NULL, 'VOCALES NRO.1', 'VOCAL PRINCIPAL', 'member', 'PRINCIPAL', 'PRINCIPAL', 1, 1, 1, NOW()),
(@client_id, 'C.C.', 'REEMPLAZA_NUM_DOC_9', 'REEMPLAZA_NOMBRE_9', NULL, 'VOCALES NRO.1', 'VOCAL PRINCIPAL', 'member', 'PRINCIPAL', 'PRINCIPAL', 1, 1, 1, NOW()),
(@client_id, 'C.C.', 'REEMPLAZA_NUM_DOC_10', 'REEMPLAZA_NOMBRE_10', NULL, 'VOCALES NRO.1', 'VOCAL PRINCIPAL', 'member', 'PRINCIPAL', 'PRINCIPAL', 1, 1, 1, NOW()),
(@client_id, 'C.C.', 'REEMPLAZA_NUM_DOC_11', 'REEMPLAZA_NOMBRE_11', NULL, 'VOCALES NRO.1', 'VOCAL PRINCIPAL', 'member', 'PRINCIPAL', 'PRINCIPAL', 1, 1, 1, NOW()),
(@client_id, 'C.C.', 'REEMPLAZA_NUM_DOC_12', 'REEMPLAZA_NOMBRE_12', NULL, 'VOCALES NRO.1', 'VOCAL PRINCIPAL', 'member', 'PRINCIPAL', 'PRINCIPAL', 1, 1, 1, NOW()),
(@client_id, 'C.C.', 'REEMPLAZA_NUM_DOC_13', 'REEMPLAZA_NOMBRE_13', NULL, 'VOCALES NRO.1', 'VOCAL PRINCIPAL', 'member', 'PRINCIPAL', 'PRINCIPAL', 1, 1, 1, NOW()),
(@client_id, 'C.C.', 'REEMPLAZA_NUM_DOC_14', 'REEMPLAZA_NOMBRE_14', NULL, 'VOCALES NRO.1', 'VOCAL PRINCIPAL', 'member', 'PRINCIPAL', 'PRINCIPAL', 1, 1, 1, NOW()),
(@client_id, 'C.C.', 'REEMPLAZA_NUM_DOC_15', 'REEMPLAZA_NOMBRE_15', NULL, 'VOCALES NRO.1', 'VOCAL PRINCIPAL', 'member', 'PRINCIPAL', 'PRINCIPAL', 1, 1, 1, NOW()),
(@client_id, 'C.C.', 'REEMPLAZA_NUM_DOC_16', 'REEMPLAZA_NOMBRE_16', NULL, 'VOCALES NRO.1', 'VOCAL PRINCIPAL', 'member', 'PRINCIPAL', 'PRINCIPAL', 1, 1, 1, NOW()),
(@client_id, 'C.C.', 'REEMPLAZA_NUM_DOC_17', 'REEMPLAZA_NOMBRE_17', NULL, 'VOCALES NRO.1', 'VOCAL PRINCIPAL', 'member', 'PRINCIPAL', 'PRINCIPAL', 1, 1, 1, NOW()),
(@client_id, 'C.C.', 'REEMPLAZA_NUM_DOC_18', 'REEMPLAZA_NOMBRE_18', NULL, 'VOCALES NRO.1', 'VOCAL PRINCIPAL', 'member', 'PRINCIPAL', 'PRINCIPAL', 1, 1, 1, NOW()),
(@client_id, 'C.C.', 'REEMPLAZA_NUM_DOC_19', 'REEMPLAZA_NOMBRE_19', NULL, 'JUNTA DE VIGILANCIA', 'JUNTA DE VIGILANCIA', 'member', 'JUNTA_DE_VIGILANCIA', 'VIGILANCIA', 1, 1, 1, NOW()),
(@client_id, 'C.C.', 'REEMPLAZA_NUM_DOC_20', 'REEMPLAZA_NOMBRE_20', NULL, 'JUNTA DE VIGILANCIA', 'JUNTA DE VIGILANCIA', 'member', 'JUNTA_DE_VIGILANCIA', 'VIGILANCIA', 1, 1, 1, NOW()),
(@client_id, 'C.C.', 'REEMPLAZA_NUM_DOC_21', 'REEMPLAZA_NOMBRE_21', NULL, 'JUNTA DE VIGILANCIA', 'JUNTA DE VIGILANCIA', 'member', 'JUNTA_DE_VIGILANCIA', 'VIGILANCIA', 1, 1, 1, NOW()),
(@client_id, 'C.C.', 'REEMPLAZA_NUM_DOC_22', 'REEMPLAZA_NOMBRE_22', NULL, 'CONTABILIDAD', 'CONTADORA', 'member', 'PRINCIPAL', 'PRINCIPAL', 1, 1, 1, NOW()),
(@client_id, 'C.C.', 'REEMPLAZA_NUM_DOC_23', 'REEMPLAZA_NOMBRE_23', NULL, 'REVISORIA', 'REVISOR FISCAL', 'member', 'PRINCIPAL', 'PRINCIPAL', 1, 1, 1, NOW()),
(@client_id, 'C.C.', 'REEMPLAZA_NUM_DOC_24', 'REEMPLAZA_NOMBRE_24', NULL, 'REVISORIA', 'REVISOR FISCAL', 'member', 'PRINCIPAL', 'PRINCIPAL', 1, 1, 1, NOW()),
(@client_id, 'C.C.', 'REEMPLAZA_NUM_DOC_25', 'REEMPLAZA_NOMBRE_25', NULL, 'REVISORIA', 'REVISOR FISCAL', 'member', 'PRINCIPAL', 'PRINCIPAL', 0, 0, 1, NOW()),
(@client_id, 'C.C.', 'REEMPLAZA_NUM_DOC_26', 'REEMPLAZA_NOMBRE_26', NULL, 'REVISORIA', 'REVISOR FISCAL', 'member', 'PRINCIPAL', 'PRINCIPAL', 0, 0, 1, NOW());

