import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const savedLanguage = localStorage.getItem('language');
    return savedLanguage || 'es';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const changeLanguage = (lang) => {
    setLanguage(lang);
  };

  const translations = {
    es: {
      product: 'Producto',
      modules: 'Módulos',
      benefits: 'Beneficios',
      contact: 'Contacto',
      heroSubtitle: 'Plataforma profesional para la gestión integral de reuniones formales de órganos colegiados',
      loginButton: 'Iniciar Sesión',
      whatIsTitle: '¿Para qué sirve esta plataforma?',
      whatIsDescription: 'BOARD QUORUM es una solución integral diseñada para optimizar y digitalizar la gestión de reuniones formales de juntas directivas, asambleas y comités. Facilita el registro de asistencia, validación de quórum, votaciones y generación de actas de manera eficiente y segura.',
      mainFeatures: 'Características Principales',
      attendanceRegistration: 'Registro de Asistencia',
      attendanceDescription: 'Gestión eficiente y automatizada de asistencia a reuniones',
      quorumValidation: 'Validación de Quórum',
      quorumDescription: 'Cálculo automático y validación de quórum según reglas configuradas',
      voting: 'Votaciones',
      votingDescription: 'Sistema completo de votaciones, registro y resultados en tiempo real',
      reports: 'Reportes y Exportaciones',
      reportsDescription: 'Generación de reportes profesionales en PDF y HTML',
      availableModules: 'Módulos Disponibles',
      boardMeeting: 'Junta Directiva',
      boardDescription: 'Gestión completa de reuniones de juntas directivas',
      createMeetings: 'Creación de reuniones',
      registerAttendance: 'Registro de asistencia',
      validateQuorum: 'Validación de quórum',
      votingResults: 'Votaciones y resultados',
      generalAssembly: 'Asamblea General',
      generalDescription: 'Gestión de asambleas generales de delegados',
      comingSoon: 'Próximamente',
      efficiency: 'Eficiencia',
      efficiencyDescription: 'Automatiza procesos manuales y reduce el tiempo de gestión de reuniones',
      traceability: 'Trazabilidad',
      traceabilityDescription: 'Registro completo y auditable de todas las decisiones y votaciones',
      security: 'Seguridad',
      securityDescription: 'Datos protegidos con encriptación y control de acceso',
      accessibility: 'Accesibilidad',
      accessibilityDescription: 'Acceso desde cualquier dispositivo, en cualquier momento',
      contactTitle: 'Contacto',
      contactSubtitle: '¿Interesado en implementar BOARD QUORUM en tu organización? Déjanos tus datos y nos pondremos en contacto contigo.',
      name: 'Nombre',
      namePlaceholder: 'Tu nombre completo',
      email: 'Email',
      emailPlaceholder: 'tu@email.com',
      organization: 'Organización',
      organizationPlaceholder: 'Nombre de tu organización',
      message: 'Mensaje',
      messagePlaceholder: 'Cuéntanos sobre tus necesidades...',
      sendMessage: 'Enviar Mensaje',
      platformTagline: 'Plataforma de gobernanza configurable',
      developedBy: 'Desarrollado por',
      selectOrganization: 'Seleccionar Organización',
      emailLabel: 'Correo Electrónico',
      passwordLabel: 'Contraseña',
      loginTitle: 'Iniciar Sesión',
      loginSubtitle: 'Accede a tu plataforma BOARD QUORUM',
      noAccount: '¿No tienes cuenta?',
      contactPivot: 'Contacta a Pivot Consulting',
      // Dashboard
      adminPanel: 'Panel de Administración',
      adminSubtitle: 'Gestión y estadísticas de BOARD QUORUM',
      totalMeetings: 'Total Reuniones',
      activeMeetings: 'Reuniones Activas',
      completedMeetings: 'Completadas',
      upcomingMeetings: 'Próximas',
      recentMeetings: 'Reuniones Recientes',
      quickActions: 'Acciones Rápidas',
      newMeeting: 'Nueva Reunión',
      viewAllMeetings: 'Ver Todas las Reuniones',
      organizations: 'Organizaciones',
      noMeetingsRegistered: 'No hay reuniones registradas',
      // Members
      memberManagement: 'Gestión de Miembros',
      newMember: '+ Nuevo Miembro',
      cancel: 'Cancelar',
      editMember: 'Editar Miembro',
      newMemberTitle: 'Nuevo Miembro',
      documentType: 'Tipo de Documento',
      selectDocumentType: 'Seleccionar Tipo de Documento',
      name: 'Nombre',
      organicRole: 'Rol Orgánico',
      selectOrganicRole: 'Seleccionar Rol Orgánico',
      position: 'Cargo',
      selectPosition: 'Seleccionar Cargo',
      votingRole: 'Rol en Votación',
      selectVotingRole: 'Seleccionar Rol en Votación',
      countsForQuorum: 'Cuenta para Quórum',
      canVote: 'Puede Votar',
      documentNumber: 'Número de Documento',
      email: 'Correo Electrónico',
      role: 'Rol',
      selectRole: 'Seleccionar Rol',
      participantType: 'Tipo de Participante',
      selectParticipantType: 'Seleccionar Tipo de Participante',
      create: 'Crear',
      update: 'Actualizar',
      edit: 'Editar',
      delete: 'Eliminar',
      noMembersRegistered: 'No hay miembros registrados',
      confirmDeleteMember: '¿Estás seguro de eliminar este miembro?',
      errorSavingMember: 'Error al guardar el miembro',
      errorDeletingMember: 'Error al eliminar el miembro',
      loading: 'Cargando...',
      // Meetings
      manageMeetings: 'Gestionar Reuniones',
      newMeetingBtn: '+ Nueva Reunión',
      noMeetings: 'No hay reuniones programadas',
      createFirstMeeting: 'Crea tu primera reunión para comenzar',
      createFirstMeetingBtn: 'Crear Primera Reunión',
      scheduled: 'Programada',
      activeStatus: 'Activa',
      completedStatus: 'Completada',
      boardMeeting: 'Junta Directiva',
      assembly: 'Asamblea',
      committee: 'Comité',
      council: 'Consejo',
      viewDetails: 'Ver Detalles',
      joinMeeting: 'Unirse',
      requestPending: 'Solicitud pendiente',
      requestAccepted: '✓ Aceptado',
      confirmDelete: '¿Estás seguro de eliminar esta reunión?',
      meetingDeleted: 'Reunión eliminada exitosamente',
      errorDeletingMeeting: 'Error al eliminar la reunión',
      confirmJoinRequest: '¿Deseas solicitar unirte a esta reunión? El administrador revisará tu solicitud.',
      joinRequestSent: 'Solicitud enviada. El administrador la revisará.',
      errorSendingRequest: 'Error al enviar la solicitud',
      editMeetingTitle: 'Editar Reunión',
      deleteMeetingTitle: 'Eliminar Reunión',
      // Login errors
      selectOrganizationError: 'Por favor selecciona una organización',
      loginError: 'Error al iniciar sesión',
      loggingIn: 'Iniciando sesión...',
      // Header
      meetings: 'Reuniones',
      members: 'Miembros',
      administration: 'Administración',
      logout: 'Cerrar Sesión',
      login: 'Iniciar Sesión',
      // Organizations
      organizationManagement: 'Gestión de Organizaciones',
      newOrganization: '+ Nueva',
      editOrganization: 'Editar Organización',
      newOrganizationTitle: 'Nueva Organización',
      organizationName: 'Nombre de la Organización',
      subdomain: 'Subdominio',
      logo: 'Logo',
      primaryColor: 'Color Primario',
      secondaryColor: 'Color Secundario',
      language: 'Idioma',
      pilotClientData: 'Datos del Cliente Piloto',
      pilotClientDescription: 'El cliente piloto será el administrador de esta organización',
      pilotName: 'Nombre del Cliente Piloto',
      pilotEmail: 'Email del Cliente Piloto',
      pilotPassword: 'Contraseña del Cliente Piloto',
      createFirstOrganization: 'Crear Primera Organización',
      confirmDeleteOrganization: '¿Estás seguro de que deseas eliminar esta organización?',
      errorLoadingOrganizations: 'Error al cargar organizaciones',
      errorSavingOrganization: 'Error al guardar la organización',
      errorDeletingOrganization: 'Error al eliminar la organización',
      organizationCreatedSuccess: 'Organización creada exitosamente',
      organizationUpdatedSuccess: 'Organización actualizada exitosamente',
      organizationDeletedSuccess: 'Organización eliminada exitosamente',
      // Meeting Detail
      meetingNotFound: 'Reunión no encontrada',
      errorActivatingVoting: 'Error al activar la votación',
      backToMeetings: 'Volver a Reuniones',
      attendance: 'Asistencia',
      votings: 'Votaciones',
      quorum: 'Quórum',
      registerAttendance: 'Registrar Asistencia',
      newVoting: 'Nueva Votación',
      activate: 'Activar',
      viewResults: 'Ver Resultados',
      // Create Meeting
      newMeetingTitle: 'Nueva Reunión',
      meetingTitle: 'Título',
      description: 'Descripción',
      date: 'Fecha y Hora',
      location: 'Ubicación',
      meetingType: 'Tipo de Reunión',
      googleMeetLink: 'Enlace de Google Meet',
      googleMeetPlaceholder: 'https://meet.google.com/xxx-xxxx-xxx',
      googleMeetHelp: 'Las reuniones se realizan en Google Meet. Comparte este enlace con los participantes.',
      createInGoogleMeet: 'Crear en Google Meet',
      votingLink: 'Link de Votaciones',
      votingLinkHelp: 'Este link se generará automáticamente y se compartirá en la reunión de Google Meet para que los participantes puedan votar.',
      creating: 'Creando...',
      createMeeting: 'Crear Reunión',
      errorCreatingMeeting: 'Error al crear la reunión',
      // Public Attendance
      selectMember: 'Selecciona tu nombre',
      selectMemberFromList: 'Selecciona tu nombre de la lista',
      memberNotFoundHelp: 'Si no encuentras tu nombre, contacta al administrador',
      attendanceRegistered: 'Asistencia Registrada',
      attendanceRegisteredSuccess: 'Tu asistencia ha sido registrada exitosamente.',
      registering: 'Registrando...',
      loading: 'Cargando...',
      meetingNotFound: 'Reunión no encontrada',
      errorLoadingMeeting: 'Error al cargar la información de la reunión',
      dateAndTime: 'Fecha y Hora',
      joinMeeting: 'Unirse a la Reunión'
    },
    en: {
      product: 'Product',
      modules: 'Modules',
      benefits: 'Benefits',
      contact: 'Contact',
      heroSubtitle: 'Professional platform for the comprehensive management of formal meetings of collegiate bodies',
      loginButton: 'Log In',
      whatIsTitle: 'What is this platform for?',
      whatIsDescription: 'BOARD QUORUM is a comprehensive solution designed to optimize and digitize the management of formal meetings of boards of directors, assemblies and committees. It facilitates attendance registration, quorum validation, voting and minutes generation efficiently and securely.',
      mainFeatures: 'Main Features',
      attendanceRegistration: 'Attendance Registration',
      attendanceDescription: 'Efficient and automated management of meeting attendance',
      quorumValidation: 'Quorum Validation',
      quorumDescription: 'Automatic calculation and validation of quorum according to configured rules',
      voting: 'Voting',
      votingDescription: 'Complete system of voting, registration and real-time results',
      reports: 'Reports and Exports',
      reportsDescription: 'Generation of professional reports in PDF and HTML',
      availableModules: 'Available Modules',
      boardMeeting: 'Board of Directors',
      boardDescription: 'Complete management of board of directors meetings',
      createMeetings: 'Meeting creation',
      registerAttendance: 'Attendance registration',
      validateQuorum: 'Quorum validation',
      votingResults: 'Voting and results',
      generalAssembly: 'General Assembly',
      generalDescription: 'Management of general assemblies of delegates',
      comingSoon: 'Coming Soon',
      efficiency: 'Efficiency',
      efficiencyDescription: 'Automates manual processes and reduces meeting management time',
      traceability: 'Traceability',
      traceabilityDescription: 'Complete and auditable record of all decisions and votes',
      security: 'Security',
      securityDescription: 'Data protected with encryption and access control',
      accessibility: 'Accessibility',
      accessibilityDescription: 'Access from any device, at any time',
      contactTitle: 'Contact',
      contactSubtitle: 'Interested in implementing BOARD QUORUM in your organization? Leave us your details and we will contact you.',
      name: 'Name',
      namePlaceholder: 'Your full name',
      email: 'Email',
      emailPlaceholder: 'your@email.com',
      organization: 'Organization',
      organizationPlaceholder: 'Your organization name',
      message: 'Message',
      messagePlaceholder: 'Tell us about your needs...',
      sendMessage: 'Send Message',
      platformTagline: 'Configurable governance platform',
      developedBy: 'Developed by',
      selectOrganization: 'Select Organization',
      emailLabel: 'Email Address',
      passwordLabel: 'Password',
      loginTitle: 'Log In',
      loginSubtitle: 'Access your BOARD QUORUM platform',
      noAccount: "Don't have an account?",
      contactPivot: 'Contact Pivot Consulting',
      // Dashboard
      adminPanel: 'Administration Panel',
      adminSubtitle: 'BOARD QUORUM management and statistics',
      totalMeetings: 'Total Meetings',
      activeMeetings: 'Active Meetings',
      completedMeetings: 'Completed',
      upcomingMeetings: 'Upcoming',
      recentMeetings: 'Recent Meetings',
      quickActions: 'Quick Actions',
      newMeeting: 'New Meeting',
      viewAllMeetings: 'View All Meetings',
      organizations: 'Organizations',
      noMeetingsRegistered: 'No meetings registered',
      // Members
      memberManagement: 'Member Management',
      newMember: '+ New Member',
      cancel: 'Cancel',
      editMember: 'Edit Member',
      newMemberTitle: 'New Member',
      documentType: 'Document Type',
      selectDocumentType: 'Select Document Type',
      name: 'Name',
      organicRole: 'Organic Role',
      selectOrganicRole: 'Select Organic Role',
      position: 'Position',
      selectPosition: 'Select Position',
      votingRole: 'Voting Role',
      selectVotingRole: 'Select Voting Role',
      countsForQuorum: 'Counts for Quorum',
      canVote: 'Can Vote',
      documentNumber: 'Document Number',
      email: 'Email',
      role: 'Role',
      selectRole: 'Select Role',
      participantType: 'Participant Type',
      selectParticipantType: 'Select Participant Type',
      create: 'Create',
      update: 'Update',
      edit: 'Edit',
      delete: 'Delete',
      noMembersRegistered: 'No members registered',
      confirmDeleteMember: 'Are you sure you want to delete this member?',
      errorSavingMember: 'Error saving member',
      errorDeletingMember: 'Error deleting member',
      loading: 'Loading...',
      // Meetings
      manageMeetings: 'Manage Meetings',
      newMeetingBtn: '+ New Meeting',
      noMeetings: 'No meetings scheduled',
      createFirstMeeting: 'Create your first meeting to get started',
      createFirstMeetingBtn: 'Create First Meeting',
      scheduled: 'Scheduled',
      activeStatus: 'Active',
      completedStatus: 'Completed',
      boardMeeting: 'Board of Directors',
      assembly: 'Assembly',
      committee: 'Committee',
      council: 'Council',
      viewDetails: 'View Details',
      joinMeeting: 'Join',
      requestPending: 'Request pending',
      requestAccepted: '✓ Accepted',
      confirmDelete: 'Are you sure you want to delete this meeting?',
      meetingDeleted: 'Meeting deleted successfully',
      errorDeletingMeeting: 'Error deleting meeting',
      confirmJoinRequest: 'Do you want to request to join this meeting? The administrator will review your request.',
      joinRequestSent: 'Request sent. The administrator will review it.',
      errorSendingRequest: 'Error sending request',
      editMeetingTitle: 'Edit Meeting',
      deleteMeetingTitle: 'Delete Meeting',
      // Login errors
      selectOrganizationError: 'Please select an organization',
      loginError: 'Error logging in',
      loggingIn: 'Logging in...',
      // Header
      meetings: 'Meetings',
      members: 'Members',
      administration: 'Administration',
      logout: 'Log Out',
      login: 'Log In',
      // Organizations
      organizationManagement: 'Organization Management',
      newOrganization: '+ New',
      editOrganization: 'Edit Organization',
      newOrganizationTitle: 'New Organization',
      organizationName: 'Organization Name',
      subdomain: 'Subdomain',
      logo: 'Logo',
      primaryColor: 'Primary Color',
      secondaryColor: 'Secondary Color',
      language: 'Language',
      pilotClientData: 'Pilot Client Data',
      pilotClientDescription: 'The pilot client will be the administrator of this organization',
      pilotName: 'Pilot Client Name',
      pilotEmail: 'Pilot Client Email',
      pilotPassword: 'Pilot Client Password',
      createFirstOrganization: 'Create First Organization',
      confirmDeleteOrganization: 'Are you sure you want to delete this organization?',
      errorLoadingOrganizations: 'Error loading organizations',
      errorSavingOrganization: 'Error saving organization',
      errorDeletingOrganization: 'Error deleting organization',
      organizationCreatedSuccess: 'Organization created successfully',
      organizationUpdatedSuccess: 'Organization updated successfully',
      organizationDeletedSuccess: 'Organization deleted successfully',
      // Meeting Detail
      meetingNotFound: 'Meeting not found',
      errorActivatingVoting: 'Error activating voting',
      backToMeetings: 'Back to Meetings',
      attendance: 'Attendance',
      votings: 'Votings',
      quorum: 'Quorum',
      registerAttendance: 'Register Attendance',
      newVoting: 'New Voting',
      activate: 'Activate',
      viewResults: 'View Results',
      // Create Meeting
      newMeetingTitle: 'New Meeting',
      meetingTitle: 'Title',
      description: 'Description',
      date: 'Date and Time',
      location: 'Location',
      meetingType: 'Meeting Type',
      googleMeetLink: 'Google Meet Link',
      googleMeetPlaceholder: 'https://meet.google.com/xxx-xxxx-xxx',
      googleMeetHelp: 'Meetings are held in Google Meet. Share this link with participants.',
      createInGoogleMeet: 'Create in Google Meet',
      votingLink: 'Voting Link',
      votingLinkHelp: 'This link will be automatically generated and shared in the Google Meet meeting so participants can vote.',
      creating: 'Creating...',
      createMeeting: 'Create Meeting',
      errorCreatingMeeting: 'Error creating meeting',
      // Public Attendance
      selectMember: 'Select your name',
      selectMemberFromList: 'Select your name from the list',
      memberNotFoundHelp: 'If you cannot find your name, contact the administrator',
      attendanceRegistered: 'Attendance Registered',
      attendanceRegisteredSuccess: 'Your attendance has been successfully registered.',
      registering: 'Registering...',
      loading: 'Loading...',
      meetingNotFound: 'Meeting not found',
      errorLoadingMeeting: 'Error loading meeting information',
      dateAndTime: 'Date and Time',
      joinMeeting: 'Join Meeting'
    }
  };

  const t = (key) => {
    return translations[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
